version: "3.0"

services:
  sct:
    image: aws_sct_mac:latest
    build: 
     context: ./
    container_name: aws_sct_mac
    hostname: oimadmin
    command: /bin/bash -c "sleep 5s; /u01/oracle/dockertools/createDomainAndStart.sh"
    ports:
      - "7001:7001"
    environment:
      - ADMIN_HOST=${DC_HOSTNAME}
      - ADMIN_PASSWORD=${DC_ADMIN_PWD}
      - CONNECTION_STRING=${DC_ORCL_HOST}:${DC_ORCL_PORT}:${DC_ORCL_SID}
      - DB_PASSWORD=${DC_ORCL_SYSPWD}
      - DB_SCHEMA_PASSWORD=${DC_RCU_SCHPWD}
      - RCUPREFIX=${DC_RCU_OIMPFX}
    volumes:
      - ${DC_DDIR_OIM}:/u01/oracle/user_projects

